name: "Hello Service Build and Push"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
     name: Maven Build
     runs-on: [ ubuntu-latest ]
     steps:
      - uses: actions/checkout@v3
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: devops4solutions/deploy-argocd-app
          path: target-repo
          token: ${{ secrets.PAT_TOKEN }}


      - name: Update tag in values.yaml
        run: |
          cd target-repo/deploy/dev
          ls
          sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" values.yaml

      - name: Configure Git
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add and commit the file
        run: |
          git add .
          git commit -m "Add sample.txt via GitHub Actions"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/devops4solutions/deploy-argocd-app.git
          git push
  