name: "Hello Service Build and Push"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    uses: devops4solutions/github-reusable-workflows/.github/workflows/ci.yaml@main
    with:
      ecr-registry: public.ecr.aws/w0f5g4k6
      ecr-repository: hello-svc
      image-tag: ${{ github.sha }}
      jar-name: helloservice-1.jar
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  push:
     name: Push Tag 
     needs: build
     runs-on: [ ubuntu-latest ]
     steps:  
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: devops4solutions/deploy-argocd-app
          path: target-repo
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update tag in values.yaml
        run: |
          pwd 
          ls -la
          cd target-repo/deploy/dev
          sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" values.yaml
          cd target-repo/deploy/test
          sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" values.yaml
          cd target-repo/deploy/prod
          sed -i "s/^  tag: .*/  tag: ${{ github.sha }}/" values.yaml
          

      - name: Configure Git
        run: |
          cd target-repo
          git config --unset-all http.https://github.com/.extraheader || true
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add and commit the file
        run: |
          cd target-repo
          git add .
          git commit -m "Updated tag in values.yaml via GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd target-repo
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/devops4solutions/deploy-argocd-app.git
          git fetch origin main
          git pull --rebase
          git push