name: "Hello Service Build and Push"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
     name: Maven Build
     runs-on: [ ubuntu-latest ]
     steps:
      - uses: actions/checkout@v3
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: devops4solutions/deploy-argocd-app
          path: target-repo

      - name: Update tag in values.yaml
        run: |
          cd target-repo/deploy/dev
          sed -i "s/^  tag: .*/  tag: ${{ env.SHA }}/" values.yaml

      - name: Commit and Push changes
        run: |
          cd target-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deploy/dev/values.yaml
          git commit -m "Update tag to ${{ env.SHA }}"
          git push

  